### ISSUE TITLE
Marketing Strategy

### ISSUE THREAD

**Issue by boilerrat** [DAOmasons/GrantShips#116]
- [ ] How will we approach marketing?

**Comment by UI369** [comment]
Some notes on Marketing Strategy from 11/15 talk w/Jord & UI : https://hackmd.io/4_G6etOjQ3OrDn4cW31uvg

**Comment by boilerrat** [comment]
Marketing Strategy "Appearances" kanban. Mostly to track potential appearances or opportunities.
https://github.com/orgs/DAOmasons/projects/18
