### ISSUE TITLE
Finalize Technical Treatment

### ISSUE THREAD

**Issue by boilerrat** [DAOmasons/GrantShips#28]
Technical treatment - outlining how the various contracts/technologies fit together.

**Comment by UI369** [comment]
- [ ] List: Transactions & Arguments called for each user (e.g. voter, operator, ref)
- [ ] List: Data Sources (for each view)

**Comment by UI369** [comment]
Technical Treatment: https://hackmd.io/HWyX2ArwSXOXZeTqOMP0YA
App Decisions: https://hackmd.io/B1yIVduZSNC8Zw_nwUOFXQ

**Comment by boilerrat** [comment]
we don't have it documented but we have a good idea of path to whitepaper so closing this.
