### ISSUE TITLE
Set Up Vendor Meeting with Allo

### ISSUE THREAD

**Issue by boilerrat** [DAOmasons/GrantShips#60]

**Comment by boilerrat** [comment]
sent TG DM to Allo. My contact there is OOO until Monday

**Comment by UI369** [comment]
TODO: Get Calendly link from Chris

**Comment by boilerrat** [comment]
Meeting Set for Monday Dec 18, 2:00 PM EST

**Comment by boilerrat** [comment]
meeting took place on Monday. Zakk offered dev help from Allo to bring our contract into line with Allo.
